services:
  mosquitto:
    image: docker.io/eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z
    restart: unless-stopped

  redis:
    image: docker.io/redis:7-alpine
    container_name: redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:Z
      - ./docker/redis/data:/data:Z
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-mqtt-datasource
    volumes:
      - ./docker/grafana/data:/var/lib/grafana:Z
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:Z
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:Z
    restart: unless-stopped
