apiVersion: 1

datasources:
  - name: MQTT
    type: grafana-mqtt-datasource
    uid: mqtt
    access: proxy
    isDefault: false
    jsonData:
      brokerUrl: tcp://mosquitto:1883
      clientId: grafana-mqtt
